{% set name = "scikit-garden" %}
{% set version = "0.1.3" %}
{% set sha256 = "d6fe65205f39633f17c181f552a0fc56e2f05bb2096be63f38c160fe20718d9d" %}
{% set build = 1 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    # These patches are needed to build on Windows; will be in next release.
    - inline-fmax.patch  # https://github.com/scikit-garden/scikit-garden/pull/44
    - setuptools.patch  # https://github.com/scikit-garden/scikit-garden/pull/49

build:
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - cython
    - toolchain
    - numpy 1.8.*  # [not (win and (py35 or py36))]
    - numpy 1.9.*  # [win and py35]
    - numpy 1.11.*  # [win and py36]

  run:
    - python
    - numpy >=1.8  # [not (win and (py35 or py36))]
    - numpy >=1.9  # [win and py35]
    - numpy >=1.11  # [win and py36]
    - scipy
    - scikit-learn >=0.18

test:
  imports:
    - skgarden
    - skgarden.mondrian
    - skgarden.quantile

about:
  home: https://scikit-garden.github.io/
  # In next release: https://github.com/scikit-garden/scikit-garden/pull/47
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.txt'
  license: BSD 3-Clause
  license_family: BSD
  summary: 'A garden for scikit-learn compatible trees'
  dev_url: https://github.com/scikit-garden/scikit-garden
  doc_url: https://scikit-garden.github.io/

extra:
  recipe-maintainers:
    - pmlandwehr
    - ukaratay
    - dougalsutherland
