appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: YnVjF7yLOSguG8AdKJWv+9gfstb9TUuVfJHK5wK4u38iRKRXi+qj929/+azYIR0CkmNZSXnKboVmpf58AOb1nQxVALrUYea1ivq/61ocP8QxaCJUVMQoSccmPCeCCzE0J3a2VPBx4CqricHUGnhqk0wENuXgKPtiWW9ghspPC2n+uNuu9F5gBMvPs3ciAX2coKCdbSC6s0XEsEBmdHjhJ24s/Bd47YaRiLkUyh6UlO4AJyVhbq01UxXx8gr81KZNs+4nLxoFOoA5oxfZG85Ni0oPF2C1JHeIoyYWjyjDZ8Tdmzh/6ro5c/AOa14dD6FjOahUcTGrxK0kgp5OL4K7SybnaSKeG2a6fhA+KvlqB5en/CrWwN4R+kjThBuN77fmNg8HrTcjc4OKUl/Y5ENz12jaJ+E0wHKpenD+xu3I5BsqFhD7CqpHqOF/TPUXTTUdTwvrlNtnKqLAux9+jo9H4+QotFzm5jWsvhHrewopMrfO7EK/rfmzUKLb9y6YIFXAc0SvFJWiEQfDNmsR47Pq74x7lRWi0i2gLESsvOhC84HAgZxofRRsWrUtBvabE0a9eq5brJ7p5X8lGTGBPucnkxdNg5ipYFubp9otxm5BZwHY2n4X5g8k7JyHeU6ers2Rrwr0AAWxnYz4ZOUQYSoTlsrmi6K5pN6e1gAeMrNrMxg=}
conda_forge_output_validation: true
