travis:
  secure:
    BINSTAR_TOKEN: JYUTF8/t5K6jjDtLAcMe1+TDlxMqXs1DZDWnmWIakFSVgjda/rDD/w77ct79CzhCgcbcOBvQJCEGlmIxVMA81Vfd0gNc7gzS3N2sbwRQlqt1e7FZr76jNidr+9EIUoim5Ge1jKi6KolUn5CXxEGOUV3MwKHkx9RMmshDkaRxbEWn1se/OliX2Cl2QN7KZzGvbWxxwWWEQTCJoBPwQPwrpJkNFoHXG6gSlPRxdb7QBF6/pUxoHWqCY+4wzeFUO9gbUu0tVnfHXQ5ZWZnWViXaZ2/Wcn6GCmTC+LzVfcXL3XORIwPyZarSyF+MQUIyHCWFPyluu9AEkrCOq8iI8do4+Khs8Gf9t9He4r1g3LtD3i0xcK49GT2y3IDD9VrFoOQtvOCvsq97TKcmoF5xTy0uyb/BY/x3qqKqZQfgPsaK1hawYJPhUVmxjn3333wSG5HWJJ6x/8rIKn+isocIeFsjU7zr23ffkJJfFlVqch6dsXiREic0S9keT5CQ29xwKOJA8XS9IslsXsIO3eoHZGEeiSlwFFThV4DhUWjr/Hux+ZwmCV5WB64uJTLMmCi4bkoQSTkQHhA1qbJoGjavAsGuJQjqrxrQuTf+sFlKBwzeEcadvN51Iez5ALpiFblIv+KRB7QMxt9e6Eq8MnFcAfyEIlNozb5nuQJv9zK1SxTxobg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
